apiVersion: v1
kind: Namespace
metadata:
  name: teamcity-server
  labels:
    app: {{ .Release.Name }}-teamcity
    component: server
---
apiVersion: v1
kind: Namespace
metadata:
  name: teamcity-agents
  labels:
    app: {{ .Release.Name }}-teamcity
    component: agents 
