apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgresql
  namespace: teamcity-server
  labels:
    app: {{ .Release.Name }}-teamcity
    component: postgres
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    app: {{ .Release.Name }}-teamcity
    component: postgres
