apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-teamcity-server
  namespace: teamcity-server
  labels:
    app: {{ .Release.Name }}-teamcity
    component: server
spec:
  type: ClusterIP
  ports:
  - port: 8111
    targetPort: 8111
    protocol: TCP
    name: http
  selector:
    app: {{ .Release.Name }}-teamcity
    component: server
